name: build

on: push

jobs:
  build:
    runs-on: >-
      ${{
        (matrix.os == 'mac' && matrix.arch == 'arm64') &&
          'macos-15' ||
          (fromJson('{"linux":"ubuntu-22.04","mac":"macos-13","win":"windows-2022"}')[matrix.os])
      }}
    continue-on-error: false

    strategy:
      fail-fast: false
      matrix:
        os: [linux, mac, win]
        arch: [x64]
        include:
          - os: mac
            arch: arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: CCache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ccache-${{ matrix.os }}-${{ matrix.arch }}

      - name: Install Windows SDK
        if: matrix.os == 'win'
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621

      - name: Install ninja
        if: matrix.os == 'win'
        uses: seanmiddleditch/gha-setup-ninja@v5

      - name: Get number of CPU cores
        uses: SimenB/github-actions-cpu-cores@v2
        id: cpu-cores

      - name: Create project (Posix)
        if: matrix.os != 'win'
        run: >
          cmake
          -S .
          -B build
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCMAKE_BUILD_TYPE=Release

      - name: Create project (Windows)
        if: matrix.os == 'win'
        run: >
          cmake
          -S .
          -B build
          -DCMAKE_C_COMPILER_LAUNCHER=ccache
          -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          -DCMAKE_BUILD_TYPE=Release
          -G Ninja
          -DCMAKE_SYSTEM_VERSION="10.0.22621.0"

      - name: Build
        run: >
          cmake
          --build build
          --config Release
          -j ${{ steps.cpu-cores.outputs.count }}

      - name: Test (Posix)
        if: matrix.os != 'win'
        run: ./build/hello_world

      - name: Test (Windows)
        if: matrix.os == 'win'
        run: ./build/Release/hello_world
